import dash
import dash_core_components as dcc
import dash_html_components as html
import dash_bootstrap_components as dbc

app = dash.Dash(__name__)

def bundle_assumption():
	return html.Div([
		html.Div(
			[
				dbc.Row([
				dbc.Col(width = 6),
				dbc.Col(html.H6("FFS Assumptions"), width = 2),
				dbc.Col(html.H6('Bundled Payment Assumptions'), width =3),
				],
				style={"text-align":"center"}),
			dbc.Row([
				dbc.Col(width = 6),
				dbc.Col(html.Hr(), width = 2),
				dbc.Col(html.Hr(), width = 3)
				]),
			dbc.Row([
				dbc.Col(html.H2('Inpatient'), style={"margin-left":"2rem", "font-size":"1.2rem"}, width = 6),
				dbc.Col(html.H6('FFS Margin'), width = 1, style={"text-align":"center", "margin-left":"-2rem"}),
				dbc.Col(html.H6('Bundle Cost Trend (under FFS)'), width = 1, style={"text-align":"center"}),
				dbc.Col(html.H6('Additional Steerage'), width = 1, style={"text-align":"center"}),
				dbc.Col(html.H6('Expected Bundle Cost Reduction'), width = 1, style={"text-align":"center"}),
				dbc.Col(html.H6('Expected Quality Improvement'), width = 1, style={"text-align":"center"}),
				]),
			html.Hr(),
			dbc.Row([
				dbc.Col(html.H1("Spine, Bone, and Joint", style={"font-size":"1rem","margin-left":"2rem","padding-bottom":"0.5rem","padding-top":"0.5rem"})),
				]),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Back and neck except spinal fusion'), width = 5),
				dbc.Col(dbc.Input(value = '4.6%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.7%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '4.9%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Double joint replacement of the lower extremity'), width = 5),
				dbc.Col(dbc.Input(value = '5.7%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '4.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Fractures of the femur and hip or pelvis'), width = 5),
				dbc.Col(dbc.Input(value = '5.3%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.3%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Hip and femur procedures except major joint'), width = 5),
				dbc.Col(dbc.Input(value = '5.1%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '4.4%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Lower extremity/humerus procedure except hip, foot, femur'), width = 5),
				dbc.Col(dbc.Input(value = '4.1%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.7%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '6.6%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Major joint replacement of the lower extremity (MJRLE)'), width = 5),
				dbc.Col(dbc.Input(value = '5.7%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.2%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Major joint replacement of the upper extremity'), width = 5),
				dbc.Col(dbc.Input(value = '5.2%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Spinal fusion'), width = 5),
				dbc.Col(dbc.Input(value = '5.2%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.7%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.9%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			html.Hr(),
			dbc.Row([
				dbc.Col(html.H1("Kidney", style={"font-size":"1rem","margin-left":"2rem","padding-bottom":"0.5rem","padding-top":"0.5rem"})),
				]),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Renal failure'), width = 5),
				dbc.Col(dbc.Input(value = '5.8%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.3%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			html.Hr(),
			dbc.Row([
				dbc.Col(html.H1("Infectious Disease", style={"font-size":"1rem","margin-left":"2rem","padding-bottom":"0.5rem","padding-top":"0.5rem"})),
				]),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Cellulitis'), width = 5),
				dbc.Col(dbc.Input(value = '5.1%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.1%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Sepsis'), width = 5),
				dbc.Col(dbc.Input(value = '4.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.1%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Urinary tract infection'), width = 5),
				dbc.Col(dbc.Input(value = '5.8%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.1%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.8%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			html.Hr(),
			dbc.Row([
				dbc.Col(html.H1("Neurological", style={"font-size":"1rem","margin-left":"2rem","padding-bottom":"0.5rem","padding-top":"0.5rem"})),
				]),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Seizures'), width = 5),
				dbc.Col(dbc.Input(value = '4.1%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.1%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '4.9%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Stroke'), width = 5),
				dbc.Col(dbc.Input(value = '4.2%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.5%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			html.Hr(),
			dbc.Row([
				dbc.Col(html.H1("Cardiac", style={"font-size":"1rem","margin-left":"2rem","padding-bottom":"0.5rem","padding-top":"0.5rem"})),
				]),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Acute myocardial infarction'), width = 5),
				dbc.Col(dbc.Input(value = '4.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.5%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '4.1%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Cardiac arrhythmia'), width = 5),
				dbc.Col(dbc.Input(value = '5.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.1%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Cardiac defibrillator'), width = 5),
				dbc.Col(dbc.Input(value = '4.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Cardiac valve'), width = 5),
				dbc.Col(dbc.Input(value = '5.7%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.9%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.2%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Congestive heart failure'), width = 5),
				dbc.Col(dbc.Input(value = '4.2%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.3%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '4.9%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Coronary artery bypass graft'), width = 5),
				dbc.Col(dbc.Input(value = '5.3%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.8%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '4.7%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.1%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Pacemaker'), width = 5),
				dbc.Col(dbc.Input(value = '4.8%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.3%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Percutaneous coronary intervention'), width = 5),
				dbc.Col(dbc.Input(value = '4.5%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.8%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '4.9%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Transcatheter Aortic Valve Replacement'), width = 5),
				dbc.Col(dbc.Input(value = '4.6%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			html.Hr(),
			dbc.Row([
				dbc.Col(html.H1("Pulmonary", style={"font-size":"1rem","margin-left":"2rem","padding-bottom":"0.5rem","padding-top":"0.5rem"})),
				]),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('COPD, bronchitis, asthma'), width = 5),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '7.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Simple pneumonia and respiratory infections'), width = 5),
				dbc.Col(dbc.Input(value = '5.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.7%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.5%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			html.Hr(),
			dbc.Row([
				dbc.Col(html.H1("Gastrointestinal", style={"font-size":"1rem","margin-left":"2rem","padding-bottom":"0.5rem","padding-top":"0.5rem"})),
				]),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Bariatric Surgery'), width = 5),
				dbc.Col(dbc.Input(value = '4.1%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.3%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Disorders of the liver excluding malignancy, cirrhosis, alcoholic hepatitis'), width = 5),
				dbc.Col(dbc.Input(value = '4.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.5%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.3%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.1%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Gastrointestinal hemorrhage'), width = 5),
				dbc.Col(dbc.Input(value = '5.8%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.4%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.1%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Gastrointestinal obstruction'), width = 5),
				dbc.Col(dbc.Input(value = '5.7%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.3%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '6.2%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Inflammatory Bowel Disease'), width = 5),
				dbc.Col(dbc.Input(value = '4.6%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '3.6%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '6.7%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			dbc.Row([
				dbc.Col(width = 1),
				dbc.Col(html.H6('Major bowel procedure'), width = 5),
				dbc.Col(dbc.Input(value = '5.2%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '2.5%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '4.2%', bs_size="sm"), width = 1),
				dbc.Col(dbc.Input(value = '4.9%', bs_size="sm"), width = 1),
				],
				style={"padding-bottom":"0.5rem"}),
			],
			style={"padding":"1rem","background-color":"#f5f5f5","border-radius":"0.5rem"}
		),
		
		html.Div(style={"height":"1rem"}),

		html.Div(
			[
				dbc.Row([
					dbc.Col(width = 6),
					dbc.Col(html.H6("FFS Assumptions"), width = 2),
					dbc.Col(html.H6('Bundled Payment Assumptions'), width =3),
					],
					style={"text-align":"center"}),
				dbc.Row([
					dbc.Col(width = 6),
					dbc.Col(html.Hr(), width = 2),
					dbc.Col(html.Hr(), width = 3)
					]),
				dbc.Row([
					dbc.Col(html.H2('Outpatient'), style={"margin-left":"2rem", "font-size":"1.2rem"}, width = 6),
					dbc.Col(html.H6('FFS Margin'), width = 1, style={"text-align":"center", "margin-left":"-2rem"}),
					dbc.Col(html.H6('Bundle Cost Trend (under FFS)'), width = 1, style={"text-align":"center"}),
					dbc.Col(html.H6('Additional Steerage'), width = 1, style={"text-align":"center"}),
					dbc.Col(html.H6('Expected Bundle Cost Reduction'), width = 1, style={"text-align":"center"}),
					dbc.Col(html.H6('Expected Quality Improvement'), width = 1, style={"text-align":"center"}),
					]),
				html.Hr(),
				dbc.Row([
					dbc.Col(html.H1("Outpatient", style={"font-size":"1rem","margin-left":"2rem","padding-bottom":"0.5rem","padding-top":"0.5rem"})),
					]),
				dbc.Row([
					dbc.Col(width = 1),
					dbc.Col(html.H6('Back & neck except spinal fusion'), width = 5),
					dbc.Col(dbc.Input(value = '5.8%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '2.7%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '5.4%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '5.1%', bs_size="sm"), width = 1),
					],
					style={"padding-bottom":"0.5rem"}),
				dbc.Row([
					dbc.Col(width = 1),
					dbc.Col(html.H6('Cardiac Defibrillator'), width = 5),
					dbc.Col(dbc.Input(value = '4.7%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '3.1%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '6.2%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
					],
					style={"padding-bottom":"0.5rem"}),
				dbc.Row([
					dbc.Col(width = 1),
					dbc.Col(html.H6('Major joint replacement of the lower extremity (MJRLE)'), width = 5),
					dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '3.3%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '6.7%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '5.0%', bs_size="sm"), width = 1),
					],
					style={"padding-bottom":"0.5rem"}),
				dbc.Row([
					dbc.Col(width = 1),
					dbc.Col(html.H6('Percutaneous Coronary Intervention'), width = 5),
					dbc.Col(dbc.Input(value = '4.8%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '3.3%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '0.0%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '4.2%', bs_size="sm"), width = 1),
					dbc.Col(dbc.Input(value = '4.9%', bs_size="sm"), width = 1),
					],
					style={"padding-bottom":"0.5rem"}),
			],
			style={"padding":"1rem","background-color":"#f5f5f5","border-radius":"0.5rem"}
		)
		
		])


app.layout = bundle_assumption()

if __name__ == '__main__':
    app.run_server(host="127.0.0.1",debug=True, port = 8052)